title: "Robby Manalo"
email: rmanalo@stetson.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hi! These are the projects I helped develop with my pod teammates 
  during my fellowship at Major League Hacking.
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: robmahalo
github_username:  robmahalo

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
